language: java
jdk:
  - oraclejdk8

before_script:
  - chmod +x ./script/integration-test-setup.sh
  - ./script/integration-test-setup.sh > src/test/resources/application.properties
  - cat src/test/resources/application.properties

script:
  - set -o pipefail
  - mvn clean -P full-test install | grep "INFO"
  - mvn clean -P full-test cobertura:cobertura-integration-test | grep -v "DEBUG"

after_success:
  - bash <(curl -s https://codecov.io/bash)
